### ISSUE TITLE
Google Map not appearing in the Screenshot

### ISSUE THREAD

**Issue by arifron** [vre2h/use-react-screenshot#30]
![download](https://user-images.githubusercontent.com/68382635/162454220-4189c715-4ed8-4b88-882c-33f3b6e0399c.png)

**Comment by leonzdev** [comment]
Google map uses a canvas of type "webgl2" which cannot be captured unless `preserveDrawingBuffer` is set to `true` when the canvas context is created. 

You can use the workaround in https://stackoverflow.com/a/55762772

**Comment by jasjamjos** [comment]
@leonzdev hi checked out the link you shared, tried to implement it didnt work, can you show a snippet of it being used in a react/nextjs component?

**Comment by leonzdev** [comment]
I have a `injectHacks.ts` with
```typescript

// @ts-nocheck
// source: https://stackoverflow.com/a/55762772
HTMLCanvasElement.prototype.getContext = function(origFn) {
    return function(type, attribs) {
        attribs = attribs || {};
        if (type === 'webgl' || type === 'webgl2') {
            attribs.preserveDrawingBuffer = true;
        }
        return origFn.call(this, type, attribs);
    };
}(HTMLCanvasElement.prototype.getContext);
  
export {}
```

Then in my `App.tsx`
```typescript
// other imports
import ‘./injectHacks’;

// other stuff

function App() {
  // some React code
}

export default App;
```

The key is to override `HTMLCanvasElement.prototype.getContext` before your map components load.

**Comment by jasjamjos** [comment]
I think its working.. tho I'm getting another error. its probably because of the library im using..  gonna post the error here just in case someone knows the solution

`Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Window'
    --- property 'window' closes the circle
    at JSON.stringify (<anonymous>)
    at en-tv-chart.132c7060.html:1:1253
    at en-tv-chart.132c7060.html:1:1279
    at en-tv-chart.132c7060.html:1:7330
en-tv-chart.132c7060.html:1 Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Window'
    --- property 'window' closes the circle
    at JSON.stringify (<anonymous>)
    at en-tv-chart.132c7060.html:1:1253
    at en-tv-chart.132c7060.html:1:1279
    at en-tv-chart.132c7060.html:1:7330
en-tv-chart.132c7060.html:1 Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Window'
    --- property 'window' closes the circle
    at JSON.stringify (<anonymous>)
    at en-tv-chart.132c7060.html:1:1253
    at en-tv-chart.132c7060.html:1:1279
    at en-tv-chart.132c7060.html:1:7330
en-tv-chart.132c7060.html:1 Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Window'
    --- property 'window' closes the circle
    at JSON.stringify (<anonymous>)
    at en-tv-chart.132c7060.html:1:1253
    at en-tv-chart.132c7060.html:1:1279
    at en-tv-chart.132c7060.html:1:7330
vendors.6f5e0d8d267cb3e63ee0.js:27 No translation data
YFKU @ vendors.6f5e0d8d267cb3e63ee0.js:27
library.237999374a0f9a719893.js:14 Uncaught ReferenceError: urlParams is not defined
    at Object.<anonymous> (library.237999374a0f9a719893.js:14:1280)
    at /G2Z (library.237999374a0f9a719893.js:20:645)
    at o (runtime.c6da8e1e9c16eccdffac.js:1:581)
    at d (runtime.c6da8e1e9c16eccdffac.js:1:430)
    at Array.a [as push] (runtime.c6da8e1e9c16eccdffac.js:1:293)
    at library.237999374a0f9a719893.js:1:47
vendors.6f5e0d8d267cb3e63ee0.js:27 No translation data
YFKU @ vendors.6f5e0d8d267cb3e63ee0.js:27
library.237999374a0f9a719893.js:14 Uncaught ReferenceError: urlParams is not defined
    at Object.<anonymous> (library.237999374a0f9a719893.js:14:1280)
    at /G2Z (library.237999374a0f9a719893.js:20:645)
    at o (runtime.c6da8e1e9c16eccdffac.js:1:581)
    at d (runtime.c6da8e1e9c16eccdffac.js:1:430)
    at Array.a [as push] (runtime.c6da8e1e9c16eccdffac.js:1:293)
    at library.237999374a0f9a719893.js:1:47
vendors.6f5e0d8d267cb3e63ee0.js:27 No translation data
YFKU @ vendors.6f5e0d8d267cb3e63ee0.js:27
library.237999374a0f9a719893.js:14 Uncaught ReferenceError: urlParams is not defined
    at Object.<anonymous> (library.237999374a0f9a719893.js:14:1280)
    at /G2Z (library.237999374a0f9a719893.js:20:645)
    at o (runtime.c6da8e1e9c16eccdffac.js:1:581)
    at d (runtime.c6da8e1e9c16eccdffac.js:1:430)
    at Array.a [as push] (runtime.c6da8e1e9c16eccdffac.js:1:293)
    at library.237999374a0f9a719893.js:1:47
vendors.6f5e0d8d267cb3e63ee0.js:27 No translation data
YFKU @ vendors.6f5e0d8d267cb3e63ee0.js:27
library.237999374a0f9a719893.js:14 Uncaught ReferenceError: urlParams is not defined
    at Object.<anonymous> (library.237999374a0f9a719893.js:14:1280)
    at /G2Z (library.237999374a0f9a719893.js:20:645)
    at o (runtime.c6da8e1e9c16eccdffac.js:1:581)
    at d (runtime.c6da8e1e9c16eccdffac.js:1:430)
    at Array.a [as push] (runtime.c6da8e1e9c16eccdffac.js:1:293)
    at library.237999374a0f9a719893.js:1:47`

**Comment by demir10x** [comment]
We can't take screenshots of Google Maps. This is because the google map component behind the scene is wrapped in an **iframe** tag which is a separate document hence the package is not able to take its screenshot.
